inherit_from: .rubocop_todo.yml

ClassAndModuleChildren:
  Enabled: false

Documentation:
  Enabled: false

HasAndBelongsToMany:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 132

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 500

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
